config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # this will add all the resources for our application
  resources :docs
  # this is to redirect the current login user to page
  authenticated :user do
  	root "docs#index", as: "authenticated_root"
  end

  # this will set the welcome/index as the root of our application
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :docs
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController

	 before_action :find_doc, only: [:show, :edit, :update, :destroy]

	def index
		@docs = Doc.where(user_id: current_user)
	end

	def show
	end

	def new
		@doc = current_user.docs.build
	end

	def create
		@doc = current_user.docs.build(doc_params)

		if @doc.save
			redirect_to @doc
		else
			render 'new'
		end
	end

	def edit
		
	end

	def update
		if @doc.update(doc_params)
			redirect_to @doc
		else
			render 'edit'
		end
	end

	def destroy
		@doc.destroy
		redirect_to docs_path
	end

	private
		def find_doc
			@doc = Doc.find(params[:id])
		end

		def doc_params
			params.require(:doc).permit(:title, :content)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.haml
= simple_form_for @doc do |f|
	= f.input :title
	= f.input :content
	= f.button :submit, class: "button"

app/views/docs/edit.html.haml
.wrapper_with_padding
	.form_wrapper
		%h1 Edit Doc!

		= render 'form'

		= link_to "Cancel", doc_path, class: "btn_cancel" 

app/views/docs/index.html.haml
.wrapper_with_padding
	#docs
		- unless @docs.blank?
			- @docs.each do |doc|
				%a{ href: (url_for [doc]) }
					.doc
						.img_container= image_tag("http://placeskull.com/300/220/f1c40f", :alt => "Your image alt gose here...")
						%p.title= doc.title
						%p.content= truncate(doc.content, length:110)
						%p.date= time_ago_in_words(doc.created_at)
		- else
			%h2 Create Doc!
			%p Lorem ipsum dolor sit amet, consectetur adipisicing elit!
			%button= link_to "Create Doc", new_doc_path

app/views/docs/new.html.haml
.wrapper_with_padding
	.form_wrapper
		%h1 New Doc!

		= render 'form'

app/views/docs/show.html.haml
.wrapper_with_padding
	#doc_show
		%h1.title= @doc.title
		%p= simple_format(@doc.content)

		.buttons
			= link_to "Edit Doc", edit_doc_path(@doc), class: "button"
			= link_to "Delete Doc", doc_path(@doc), method: :delete, data: { confirm: "Are pretty sure?" }, class: "button"

app/views/layouts/application.html.haml
!!!
%html
%head
  %title iDoc | Ruby on Rails
  = csrf_meta_tags
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
%body
  %header
    .header_inner
      = link_to "iDoc Logo", root_path, id: "logo"

      %nav
        - if user_signed_in?
          = link_to "New iDoc", new_doc_path
          = link_to "Sign Out", destroy_user_session_path, method: :delete

        - else
          = link_to "Log In", new_user_session_path
          
  .notification_wrapper
    %p.notice= notice
    %p.alert= alert

  = yield

app/views/welcome/index.html.haml
#banner
	.banner_content
		%h1 Important Heading
		%p Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quia magni nisi repudiandae repellat quisquam suscipit voluptas!
		%button= link_to "CTA Button", new_user_registration_path

#callouts
	.callout_inner
		.wrapper
			.callout
				%h2 Sub Heading
				%p Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni esse animi accusantium ex facilis in ipsum perspiciatis commodi officiis ea debitis consequatur non, ratione tenetur quis, cupiditate. Similique, maxime natus.

#bottom_cta
	.wrapper
		%h2 Invite Heading
		%p Lorem ipsum dolor sit amet, consectetur!
		%button= link_to "CTA Button", new_user_registration_path